# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
os:
  open: "bash -c 'open {{filename}}'"
git:
  overrideGpg: true
  ignoreWhitespaceInDiffView: true
  pagers:
    - colorArg: "never"
      pager: ydiff -p cat -s --wrap --width={{columnWidth}}
    - pager: delta --paging=never # other configs in gitconfig
gui:
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 99
  border: "single"
  showPanelJumps: true
  showFileTree: true
  sidePanelWidth: 0.22
  showBottomLine: false
  theme:
    activeBorderColor:
      - '#f4dbd6'
      - bold
    inactiveBorderColor:
      - '#a5adcb'
    searchingActiveBorderColor:
      - '#eed49f'
    optionsTextColor:
      - '#8aadf4'
    selectedLineBgColor:
      - '#363a4f'
    inactiveViewSelectedLineBgColor:
      - '#6e738d'
    cherryPickedCommitFgColor:
      - '#f4dbd6'
    cherryPickedCommitBgColor:
      - '#494d64'
    markedBaseCommitFgColor:
      - '#8aadf4'
    markedBaseCommitBgColor:
      - '#eed49f'
    unstagedChangesColor:
      - '#ed8796'
    defaultFgColor:
      - '#cad3f5'

  authorColors:
     '*': '#b7bdf8'
notARepository: "quit"
promptToReturnFromSubprocess: false
keybinding:
  files:
    commitChangesWithEditor: <disabled>
customCommands:
  - key: "C"
    context: "files"
    description: "Run OpenCommit"
    command: "opencommit -y"
    output: "none"
    loadingText: "Generating commit message.."
  - key: "<c-r>"
    context: global
    description: "Open repository in browser"
    command: "gh repo view --web"
  - key: "I"
    context: "localBranches"
    description: "Rebase onto upstream"
    command: "git rebase --autostash --keep-empty --no-autosquash --rebase-merges refs/remotes/upstream/{{.SelectedLocalBranch.Name}}"
    output: "log"
